### ISSUE TITLE
Receiving: BASTA WARNING No taxon found with custom mapping file

### ISSUE THREAD

**Issue by dnieuw** [timkahlke/BASTA#11]
Hello, 

I am trying to use BASTA on some DIAMOND tsv output. When I run basta sequence, however, I get a warning `# [BASTA WARNING] No taxon found for 1346611` and the basta output file contains only "unknown" annotations.

My DIAMOND output looks as follows:
`T070O:00666:05788\tWP_005933513.1_853\t78.3\t69\t15\t0\t208\t2\t1\t69\t1.7e-24\t119.0`
I have created a custom config file to indicate that the first column is the read_id, the second is the annotation_id, etc. 

`WP_005933513.1_853` is basically the accession number and the taxon id concatenated by a "_", but in order to perform the mapping with BASTA I have created a mapping file, mapping each annotation_id to the corresponding taxon_id like this:
`WP_005933513.1_853\t853`
I have created a mapping db of that file using `basta create_db`.

I think that I have done everything I should correctly, but BASTA is unable to find the taxon eventhough I can find the taxon in the mapping file and the taxdump I downloaded using grep. I'm out of ideas...

**Comment by timkahlke** [comment]
Hi,

I agree that it looks like you did everything right. 
BASTA seems to understand your DIAMOND input file because it resolves at least one of the hits to a taxonID (1346611) which in turn it can't resolve to a taxon. So the mapping db and input files should be correct. The warning that it can't resolve the taxonID could be due to an old (or new) NCBI entry not found in the complete_taxa database but doesn't necessarily mean that something is wrong.

Another possibility is that everything is working fine but there are no conclusive LSAs for your sequences. Could you run it again and check the verbose output file (-v FILE_NAME) to see what the individual hits look like?
