### ISSUE TITLE
running Basta on already downloaded mapping file

### ISSUE THREAD

**Issue by Jigyasa3** [timkahlke/BASTA#23]
Hey @timkahlke 

I followed the tutorial on how to create a database on already downloaded NCBI mapping file <https://github.com/timkahlke/BASTA/wiki/2.-Initial-Setup#1-download-ncbi-sequence-databases>.

The steps I am running-
$wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz #custom for nr database
$gunzip prot.accession2taxid.gz
$/work/BASTA-1.3.2.3/bin/basta create_db prot.accession2taxid prot_mapping.db 1 2
#create_db, using second column (1)->to get new accession ids (eg-WP_090162531.1) , and third column (2)-to get taxids

$/work/BASTA-1.3.2.3/bin/basta sequence basta-COG0552.txt basta-result-COG0552.txt prot
#running the basta on blast output

When I try the new database on my blast output, I get an empty result. Whereas just "grepping" the accession number to the prot.accession2taxid gives an output.

Where am I going wrong? (Using basta on uniref90 database works though)

**Comment by timkahlke** [comment]
Hey @Jigyasa3,

Could you try importing the mapping file again with indices 0 2 instead of 1 2 and see if it works then? 

Cheers,
Tim

**Comment by Jigyasa3** [comment]
Hey @timkahlke 

Thanks for the suggestion. I tried importing the mapping file with indices 0 and 2, but it's still not working.

Here are the file format and codes that I am using-
#blast results file-
$head blast_results.txt
contig_1   WP_090162531.1  66.7    315     98      1       28      342     6       313     5.2e-110        407.5

$ head prot.accession2taxid #the mapping file
accession       accession.version       taxid   gi
A0A023GPI8      A0A023GPI8.1    232300  1027923628
A0A023GPJ0      A0A023GPJ0.2    716541  765680613

#the code for creating a db-
$/work/student/jigyasa-arora/BASTA-1.3.2.3/bin/basta create_db prot.accession2taxid protnew_mapping.db 0 2

#basta command-
$/work/student/jigyasa-arora/BASTA-1.3.2.3/bin/basta sequence blastresults.txt bastatest.txt protnew

**Comment by timkahlke** [comment]
Hmm, would you mind sharing the balst output file (or the first  few thousand lines)? Makes it easier to spot the problem.

**Comment by Jigyasa3** [comment]
Here are two examples-
I have extracted out single-copy marker genes (called as mOTU) from metagenome bins, followed by Dimond blast search against the NCBI nr database.
Ultimately I want to run "basta mutiple"  command combining multiple blast outputs per bin together.

Link to blast outputs-https://drive.google.com/drive/folders/1V3QIk0MvjyvJfJ3FXDXG52vtPEDYdOTa?usp=sharing

Thanks for helping!

**Comment by timkahlke** [comment]
Hi @Jigyasa3,

I had a look at it and, unfortunately for you, it works fine for me (I used the indices 0 and 2 for import).

A few things:

1. Do you get a lot of warnings like this: "# [BASTA WARNING] No mapping found for XXXX"? If BASTA doesn't find a hit in the mapping file it will report that. It's common to not find a few but it shouldn't happen for all. If so it's an indication that something went wrong in the import

2. In the files you sent there are lots of hits with <80% identity which is the BASTA default. Try running it with a lower percent identity, e.g. 60% (-i 60). Additionally, have a look what happens if you include sequences with only one hit (default is a minimum of 3) using the -m 0 option.

Let me know how you go,
Tim
3. Did you try the

**Comment by Jigyasa3** [comment]
Dear @timkahlke 

Thanks for the suggestion to change the default percent identity! It's working now!
As I said in my previous post, I want to run basta multiple on these blast result files. 

I have changed the line 110 in AssignTaxonomy.py script, but even though I follow the BASTA wiki on running basta multiple, I am getting the following error-

My folder looks like this-
$ls folder_1
basta-COG0016.txt  basta-COG0088.txt  basta-COG0102.txt  basta-COG0215.txt
basta-COG0018.txt  basta-COG0091.txt  
#these are my blast result files.
 
$/work/student/jigyasa-arora/BASTA-1.3.2.3/bin/basta multiple -i 60 -m 0 folder_1 bastaresult-folder1.txt protnew

error-
####  Assigning one taxonomy for each file ###


# [BASTA STATUS] Assigning taxonomies ...

# [BASTA STATUS] Initializing taxonomy database

# [BASTA STATUS] Initializing mapping database

# [BASTA STATUS] - Estimating Last Common Ancestor for file  basta-COG0099.txt
Traceback (most recent call last):
  File "/work/student/jigyasa-arora/BASTA-1.3.2.3/bin/basta", line 115, in <module>
    main.run_basta(args)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/BastaMain.py", line 80, in run_basta
    self._basta_multiple(args)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/BastaMain.py", line 121, in _basta_multiple
    assigner._assign_multiple(args.blast,db_file,args.best_hit)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/AssignTaxonomy.py", line 101, in _assign_multiple
    lca = self._assign_single(os.path.join(blast_dir,bf),db_file)
TypeError: _assign_single() takes exactly 4 arguments (3 given)

**Comment by timkahlke** [comment]
Hi @Jigyasa3 ,

Cool that it works now. Sorry, the new problem is my fault. It's a bug that I haven't fixed yet. A work around for you is to delete line 95 in file /home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/AssignTaxonomy.py:

`(tax_lookup, map_lookup) = `self._get_lookups(db_file)`

After you removed that line everything should work.

**Comment by Jigyasa3** [comment]
Hey @timkahlke 

Thanks for the suggestion! I commented out line 95 from file /home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/AssignTaxonomy.py.

But I am still getting the same error-
$ /work/student/jigyasa-arora/BASTA-1.3.2.3/bin/basta multiple -i 50 -m 0 301-92.bin.97.fa-fetchmoutput bastaresult-301-92.bin.97.txt protnew
"
####  Assigning one taxonomy for each file ###


# [BASTA STATUS] Assigning taxonomies ...

# [BASTA STATUS] - Estimating Last Common Ancestor for file  basta-COG0099.txt
Traceback (most recent call last):
  File "/work/student/jigyasa-arora/BASTA-1.3.2.3/bin/basta", line 115, in <module>
    main.run_basta(args)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/BastaMain.py", line 80, in run_basta
    self._basta_multiple(args)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/BastaMain.py", line 121, in _basta_multiple
    assigner._assign_multiple(args.blast,db_file,args.best_hit)
  File "/home/j/jigyasa-arora/.local/lib/python2.7/site-packages/BASTA-1.3.2.2-py2.7.egg/basta/AssignTaxonomy.py", line 101, in _assign_multiple
    lca = self._assign_single(os.path.join(blast_dir,bf),db_file)
TypeError: _assign_single() takes exactly 4 arguments (3 given)
"

**Comment by timkahlke** [comment]
Hi again,

Sorry, again my fault. You'll also have to change line 101 from

`lca = self._assign_single(os.path.join(blast_dir,bf),db_file)`

to 

`lca = self._assign_single(os.path.join(blast_dir,bf),db_file,best)`

meaning you will have to add the ",best" at the end.

**Comment by Jigyasa3** [comment]
thank you , it's working now!

**Comment by timkahlke** [comment]
Corrected in v1.4+

**Comment by jusail** [comment]
Hi, 
i have run basta for a output file generated from diamond . My command looks  as following:-
>basta sequence -l 25 -i 80 -e 0.00001 -m 3 -b 1 -p 60 total.protein.diamond2uniprot_trembl PIGC90.dmnd.lca.out prot

when i run this i found something like this:-
#### Assigning taxonomy to each sequence ###


# [BASTA STATUS] Assigning taxonomies ...

# [BASTA STATUS] Initializing taxonomy database

# [BASTA STATUS] Initializing mapping database

# [BASTA WARNING] No taxon found for 2596922

# [BASTA WARNING] No taxon found for 2545414

# [BASTA WARNING] No taxon found for 2049333

# [BASTA WARNING] No taxon found for 2604327

# [BASTA WARNING] No taxon found for 2583375

# [BASTA WARNING] No taxon found for 741091

# [BASTA WARNING] No taxon found for 2529856

# [BASTA WARNING] No taxon found for 2478744

# [BASTA WARNING] No taxon found for 2478745

# [BASTA WARNING] No taxon found for 2586910

# [BASTA WARNING] No taxon found for 2687303

#### Done. Output written to PIGC90.dmnd.lca.out

Myouput file looks like this:-

k87_16751_6	Archaea;	Bacteria;Bacteroidetes;Bacteroidia;Bacteroidales;Prevotellaceae;Prevotella;Prevotella_oris;
k87_176724_2	Archaea;	Archaea;Euryarchaeota;Methanomicrobia;Methanomicrobiales;unknown;unknown;methanogenic_archaeon_mixed_culture_ISO4-G1;
k87_42743_2	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;	Archaea;Euryarchaeota;Methanomicrobia;Methanomicrobiales;unknown;unknown;methanogenic_archaeon_mixed_culture_ISO4-G1;
k87_84389_2	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;Methanomassiliicoccales;Methanomassiliicoccaceae;Candidatus_Methanoplasma;Candidatus_Methanoplasma_termitum;
k87_109407_2	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;Methanomassiliicoccales;Candidatus_Methanomethylophilaceae;Candidatus_Methanomethylophilus;Candidatus_Methanomethylophilus_sp.;
k87_1137_1	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;Thermoplasmatales;unknown;unknown;Thermoplasmatales_archaeon_BRNA1;
k87_53852_2	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;	Archaea;Candidatus_Thermoplasmatota;Thermoplasmata;Methanomassiliicoccales;Candidatus_Methanomethylophilaceae;Candidatus_Methanomethylophilus;Candidatus_Methanomethylophilus_alvus;


Now my question is:-
1. Is my command is right, or do i need to change some parameters.
2. The output command of run showing No taxon found can be a negligible one or not
3. Then whether the output file usually looks like or something else(I didn't got any heading for my column). Also why i am having 2 columns  in my output file.

It will really helpful if someone can just evaluate my observation .

Thank You

**Comment by timkahlke** [comment]
Hi,
1. The parameters work, although you could leave the -m and -i because -m 3 and -i 80 are the default values. Also try -b True instead of 1. That might explain why you only have 2 and not 3 columns. Never tried 1. I would expect it to be the same but who knows?! 

2. The warning says that your diamond file contains hits to a sequence that is missing from the global NCBI taxonomy that your BASTA is using. Reasons could be that your diamond db is older than the NCBI taxonomy and those IDs were removed from it. Or maybe the NCBI file is older and the new sequences in your diamond database are not yet in the NCBI taxonomy. You have basically 3 choices: ignore them and assume it wouldn't change the outcome (would make me un-easy but it's a choice). Make the parameters more stringent, e.g., set the minimum length higher, ans see if that removes the errors. If so, then the hits to the unknown taxonomies were shorter hits and could be ignored. Last, you could manually check a few of them, e.g., by searching the protein mapping file for the accession number and then googling that one. My hunch is that it's different/new/old strains of sequences you already have in your hit. In that case you can again ignore them as they won't affect the final taxonomy. The risk is of course that it's really good hits to something completely different than what you get if you ignore them. That would make the current results wrong. You could also try to find an updated version of the diamond or NCBI database or, if you wanted to, manually add the ID tot he prot mapping file and match it to the proper species on the NCBI page. But not sure if that's too much work.

3. Yeas, the output looks correct for a normal BASTA run without -b True. First column is the sequence in your initial fasta file that you used diamond on, second column is the taxonomy BASTA assigned to it. You should have a third column though that shows the best hit from the diamond output file. See the first point in this answer for more info.

Hope this helps

**Comment by jusail** [comment]
Thanks a lot for the time and suggestion you have given on it. I will do
the changes as you have suggested and will get back to you if I have any
questions arise.

Thank you

**Comment by wanboqi** [comment]
@timkahlke Hi, I'm having the same problem. The sequence doesn't match. The steps I am running：
#make Uniprot TrEMBL database
diamond makedb --in /home/public/database/Uniprot/uniprot_trembl.fasta.gz -d /home/public/database/Uniprot/new_create/uniprot_trembl

#aligning protein sequence of gene catalog to the Uniprot TrEMBL database
diamond blastp -q /home/wbq/test/data/04_Gene_Catalog/new2/total.protein.faa.90 -d /home/public/database/Uniprot/uniprot_trembl.dmnd -p 8 -e 1e-5 -k 50 --id 30 --sensitive -o /home/wbq/test/data/04_Gene_Catalog/new2/Taxonomy/total.protein.faa.90.diamond2uniprot_trembl   

basta create_db /home/public/database/Uniprot/idmapping_selected.tab uniprot1_mapping.db 0 2

basta sequence -l 25 -i 80 -e 0.00001 -m 3 -b 1 -p 60 /home/wbq/test/data/05_Taxonomy/total.protein.faa.90.diamond2uniprot_trembl_new  /home/wbq/test/data/05_Taxonomy/Allsample90.diamond2uniprot_trembl.dmnd.lca.out uniprot 

Then I get the following information，and I'm just going to give you one line, because everything else is pretty much the same：# [BASTA WARNING] No mapping found for A0A930JQK2

I would like to ask you how to solve it.Thanks!

**Comment by timkahlke** [comment]
Hi,

Could you post a line from you /home/public/database/Uniprot/idmapping_selected.tab, pls?
Otherwise, uniprot should already be included in the uni mapping database that comes with BASTA that you can download with `basta download uni`

**Comment by wanboqi** [comment]
![6JYVX6U%5CH9Z)EDSKJSE`E](https://github.com/timkahlke/BASTA/assets/125441305/d3849001-3067-47d1-94c6-4aa24979a8af) such as like this

**Comment by timkahlke** [comment]
If it's not a typo then you don't use the mapping database that you created.
The mapping type was called `uniprot1` but you specify the database `uniprot` in your `basta sequence` call.

If that's not it then 2 more things you could check
1. Make sure the accession number  `A0A930JQK2` is actually included on index 0 in your mapping file, e.g., with grep
2. Make sure the mapping file is tab-separated (could be that something goes wrong in the import ... although that should be already checked on import)

**Comment by wanboqi** [comment]
@timkahlke after i use `basta download uni` to download the uniprot database,should i use the command`basta create_db idmapping_selected.tab uniprot_mapping.db 0 12`? i am not sure that whether parameters 0 and 12 are correct,Thanks!

**Comment by timkahlke** [comment]
No, the `basta download uni` one will create the database for you. Just run `basta sequence ...` and use "uni" as the mapping type.

**Comment by wanboqi** [comment]
@timkahlke I'm sorry I'm still confused and bothered you. If I understand you correctly, you mean run the command `basta sequence total.protein.faa.90.diamond2uniprot_trembl Allsample90.diamond2uniprot_trembl.dmnd.lca.out uni` directly.But in fact I get an error '# [BASTA ERROR] No database uni_mapping.db found in /home/wbq/.basta/taxonomy. Did you forget to create the specified database or was it a typo?',Since running this command `basta download uni` only downloads the file idmapping_select.tab.gz,and no database.Sorry again to bother you so much time, because I just started to get involved in this data analysis.Looking forward to your reply,Thanks!

**Comment by timkahlke** [comment]
Sorry, my fault. The `download uni` command puts the mapping into the prot database. 
So yes, it downloads the mapping file you mentioned but then either creates or appends the database prot_mapping.db. Please try to run the basta sequence command with prot not uni. That should work.

**Comment by wanboqi** [comment]
@timkahlke Thanks for your reply! Yes, that works. But it still shows # [BASTA WARNING] No mapping found for.... Is it possible that there is something wrong with my input file, which leads to no match? I want you to have a look at my inputfile **total.protein.faa.90.diamond2uniprot_trembl**  whether there is a
![O75_A74(YT9AC6JD76Q4X79](https://github.com/timkahlke/BASTA/assets/125441305/6ddcc1ae-f797-4bc3-a474-34dbdfb1de13)
 problem, it is using diamond blastp and uniport_trembl to compare and Output the file

**Comment by timkahlke** [comment]
That also looks good. Does it find any of the sequences or none at all?
Also, did you check that all the sequences from your database are actually included in the mapping file?

**Comment by wanboqi** [comment]
@timkahlke  Yeah, you're right. I noticed my sequence wasn't in the match file. But when I go to uniport for idmapping, it exists. For example, if I search for A0A1H4C443 in uniport, it will find entry,entry name,protein names,gene names, and so on. So why is there no uniport sequence in the idmapping file?

**Comment by timkahlke** [comment]
Because it's obsolete. From Uniprot when you put in A0A930JQK2:

`Entry history: This entry is obsolete since release 2024_02/2024_02`

Explanation is your database you used to blast against does still contain obsolete entries that are not in uniprot or the mappings anymore.

If you find a mapping file for the database version you used you can build your own mapping db and everything should work again.

**Comment by JianpingQuan** [comment]
@timkahlke Hi kahlke, when I run the following command:

basta sequence -l 100 -i 80 -e 0.00001 -m 3 -b True /data1/qjp/thisStudy.diamond2uniport_trembl.out /home/quanjp/uniport/thisStudy.diamond2uniport_trembl.lca.uni.out prot

I noticed that the final output does not contain any kingdom information. For example:

k141_28391_2      unknown;Bacillota;Clostridia;Lachnospirales;Lachnospiraceae;Eisenbergiella;     unknown;Bacillota;Clostridia;Lachnospirales;Lachnospiraceae;Eisenbergiella;Eisenbergiella_porci;

All kingdom entries are labeled as unknown.

Could you please help me understand what might be causing this issue?

Thanks in advance for your help!
