### ISSUE TITLE
error when using GTDB mapping file in create_db

### ISSUE THREAD

**Issue by Jigyasa3** [timkahlke/BASTA#28]
Hey @timkahlke 

I am using a custom mapping database from GTDB in the format specified in the wiki. But when I use it for `create_db` command, it gives the following error-

mapping file-
accession       accession.version       taxid   gi
GCA007129655    GCA007129655.1  2022
GCF000979455    GCF000979455.1  669
GCA007280465    GCA007280465.1  3546
GCF000025865    GCF000025865.1  4262
GCA004525545    GCA004525545.1  3017
GCA007118145    GCA007118145.1  2546

code used-
`/home/j/jigyasa-arora/local/BASTA/bin/basta create_db accession2taxid.tsv prot_mapping.db 0 2`

error-
Creating database

 [BASTA STATUS] Reading mapping file
This might take a while, please be patient ...

Traceback (most recent call last):
  File "/home/j/jigyasa-arora/local/BASTA/bin/basta", line 115, in <module>
    main.run_basta(args)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/BASTA-1.3.2.3-py3.7.egg/basta/BastaMain.py", line 86, in run_basta
    self._basta_create_db(args)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/BASTA-1.3.2.3-py3.7.egg/basta/BastaMain.py", line 171, in _basta_create_db
    dbutils.create_db(args.directory,args.input,args.output,args.key,args.value)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/BASTA-1.3.2.3-py3.7.egg/basta/DBUtils.py", line 67, in create_db
    lookup.put(ls[i1],ls[i2])
TypeError: Argument 'key' has incorrect type (expected bytes, got str)

**Comment by timkahlke** [comment]
Hi @Jigyasa3 
Could you please check that the mapping file has tabs not spaces as separators? I have a hunch that that's the problem.

**Comment by Jigyasa3** [comment]
Hey @timkahlke 

Thanks for replying! Yes, I checked it is tab-separated. Here is the link to the file- [https://github.com/Jigyasa3/errors/blob/master/2-accession2taxid.tsv](url)

Any suggestions?

**Comment by timkahlke** [comment]
The file imports without problems for me if I use a clean/new database name. 
Could you please rename the database to something new like gtdb_mapping.db? It could be that you already created the prot_mapping.db and that causes the key error.

**Comment by Jigyasa3** [comment]
Hey @timkahlke 

I tried what you suggested, but I am still getting the same error.
`/home/j/jigyasa-arora/local/BASTA/bin/basta create_db 2-accession2taxid.tsv gtdb_mapping.db 0 2`

I am using python/3.7.3 on a computing cluster. 

Error-
Creating database

 [BASTA STATUS] Reading mapping file
This might take a while, please be patient ...

Traceback (most recent call last):
  File "/home/j/jigyasa-arora/local/BASTA/bin/basta", line 115, in <module>
    main.run_basta(args)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/BASTA-1.3.2.3-py3.7.egg/basta/BastaMain.py", line 86, in run_basta
    self._basta_create_db(args)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/BASTA-1.3.2.3-py3.7.egg/basta/BastaMain.py", line 171, in _basta_create_db
    dbutils.create_db(args.directory,args.input,args.output,args.key,args.value)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/BASTA-1.3.2.3-py3.7.egg/basta/DBUtils.py", line 67, in create_db
    lookup.put(ls[i1],ls[i2])
TypeError: Argument 'key' has incorrect type (expected bytes, got str)

**Comment by timkahlke** [comment]
HI @Jigyasa3,
Sorry, I didn't read the output properly you posted. The problem is that BASTA currently doesn't support python3 but you're trying to run it under python3 ... Please install it under python2 until I'm done with the new version. I'm working on it but will take a few more weeks.

**Comment by Jigyasa3** [comment]
Hey @timkahlke 

Thanks for pointing that out. Things are running smoothly now. I do have a follow-up question. I am using GTDB database (https://gtdb.ecogenomic.org/downloads) to annotate my metagenome contigs. GTDB is exclusively for Archaea and Bacteria. When I map the GTDB ids to NCBI ids and annotate them via LCA using BASTA, the contigs that were annotated as bacterial/archaeal in NR database, get annotated as Eukaryotic. But GTDB doesn't have Eukaryotic sequences! I have tried different LCA cutoff to ensure that spurious hits are not generating the results (by changing the -m parameter). Any suggestion on this?

for example, the contigs annotated via NR are bacteria, but when annotated via GTDB are Eukaryotic-
                                V2                                           ncbi_taxonomy_meganLCA
1 301-92_NODE_1000274number1000274      s__Aminobacterium colombiense
2 301-92_NODE_1000379number1000379             s__Treponema caldarium

gtdb_taxonomy_bastaLCA
1 Eukaryota; (8)
2 Eukaryota; (5)

**Comment by Jigyasa3** [comment]
I have a follow-up question. Would it be possible to get the final taxonomic annotation in GTDB annotation format and not the NCBI one?
For example, Epsilonproteobacteria is renamed as a separate phyla in GTDB.

**Comment by timkahlke** [comment]
Hi @Jigyasa3 ,

To answer both questions here a little bit about how BASTA works. It always uses 2 databases:
1. The _complete_taxa.db_ located in BASTA's taxonomy directory. For every taxonID it returns the NCBI taxonomy string, e.g. "Bacteria; Gammaproteobacteria ..."
2. A mapping database, also located in the taxonomy directory, that returns the correct NCBI taxonID for a sequence identifier, e.g. uniprot proteinID -> NCBI taxonID
3. 
BASTA doesn't care what's in the 2 databases. It takes the hit-contig ID, looks in the mapping database for the TaxonID and then looks for the NCBI taxon string of that taxonID in the complete_taxa.db database


To answer the first question:
As you already said, GTDB does not contain Eukarytes but your mapping file that you imported into the mapping database seems to point to taxonIDs that are eukaryotic in the NCBI database, hence your GTDB mapping file is wrong (or you imported it wrong). Maybe check a few taxonIDs manually on the NCBI taxonomy page

To answer your second question
It's possible but in the current BASTA version not very intuitive, unfortunately. You will have to create a GTDB taxonID->taxon_string database with create_db (call it whatever you want) and then rename it to "complete_taxa.db" in BASTA's taxonomy directory. But make sure you rename the original complete_taxa.db first to something else, otherwise you'll overwrite it and will have to re-download and format it later again. When you've done that you need to create a mapping database that just maps the GTDB taxonID to itself, ie., use a mapping file that just has the same taxonID twice per row.
If you call BASTA now it will look up the taxonID in the mapping file (which maps to itself) and then look for the taxon string in the complete_taxxa.db which now contains the GTDB taxonomy

... sorry that it's not easier. I'm working on the next version which will make that much more intuitive/easy.

**Comment by Jigyasa3** [comment]
Hey @timkahlke 

Thank you for the advice! Sorry, I am replying two months later. I tried what you suggested.

What I did-
##create a gtdb database in `home/.basta/taxonomy` folder-
`basta create_db /flash/BourguignonU/DB/gtdb_to_diamond/gtdb_ver89/gtdb_to_diamond/accession2taxid.tsv gtdb_mapping.db 0 2`

##rename the gtdb_mapping.db file as complete_taxa.db file while keeping the original one (renamed too)

##create a new mapping database that maps the taxid twice. 
`basta create_db /flash/BourguignonU/DB/gtdb_to_diamond/gtdb_ver89/gtdb_to_diamond/accession2taxid.tsv gtdb_mapping.db 2 2`

##basta on diamond blastp results of protein sequences in a contig-
`basta single -i 10 -m 0 gtdb-ver89-matches-230-12-contig5proteins.faa.txt bastaresult-gtdb-ver89-matches-230-12-contig5proteins.faa.txt gtdb`

Everything runs smoothly, but the output is Unknown. I examined `basta single` and `basta sequence` on the blast output file. They should be annotated as something because they were annotated as Proteobacteria via KRAKEN2 (using GTDB database). Where do you think it's going wrong? The database generation step is incorrect?

Please let me know if you would like me to share some files to reproduce the analysis.
Looking forward to your reply!

**Comment by timkahlke** [comment]
Hi @Jigyasa3,

Have a look at the details/verbose file to see what kind of hits BASTA considers. Maybe the hits are too diverse?

Tim
