### ISSUE TITLE
No mappings found

### ISSUE THREAD

**Issue by ceolder** [timkahlke/BASTA#36]
Hi,

I've been trying to use basta on output from diamond. I believe my diamond results are in the correct format that is default for basta (-outfmt 6) and the accession I'm finding (via grep) are in the prot.accession2taxid.FULL that was used to generate my database, however I am not getting any taxa names whjen I run basta.

Here is an example line for my basta input:
`M01019:41:000000000-A5RV8:1:1114:11342:10949    MBS1567671.1    92.2    51      4       0       2       154     139     189     1.43e-26        107`

When I use basta, I then get "No mapping found for MBS1567671" and the resulting output file has everything as "unknown". 
It looks like for some reason basta is ignoring the ".1", so although it should search for MBS1567671.1 it's searching for MBS1567671. Both my diamond and basta databases were generated using the same version of the prot.accession2taxid.FULL. 

It looks like this is a similar issue to one previously posted: https://github.com/timkahlke/BASTA/issues/11. I attempted re-ran with -v and the file just has all my query sequence names in this format:
```
###M01019:41:000000000-A5RV8:1:1101:14530:2789


###M01019:41:000000000-A5RV8:1:1101:12152:2947 
```
Any idea what I might need to do to fix this?

**Comment by timkahlke** [comment]
Hi,

That is weird indeed. First, that BASTA looks for the accession without the ".1" is correct. The number after the accession number is the version of the sequence. This version is removed during blast/diamond output file parsing. Reason is that the mapping databases are created from the accession numbers (column 1 in the mapping files) and not from the version numbers (column 2 in the mapping files). So searching the mapping database for accession.version wouldn't help.

The question is why it's not in the mapping database when you created it correctly. Could you post

- the command(s) you used to create the general databases
- the command you used to create the mapping file
- the BASTA call you ran

**Comment by ceolder** [comment]
Thanks for responding so quickly!
Hm... so maybe it's due to the format of the prot.accession2taxid.FULL file, which has only 2 columns, accession.version and taxid. Will BASTA automatically remove the version from the accession.version column it when it creates the database or do I need to do this first, and then create the database from that?

Generate database:
`basta create_db prot.accession2taxid.FULL /caitlin/Cyanobacteria/basta_prot_full_mapping.db 0 1`

I downloaded mapping (prot.accession2taxid.FULL.gz) from NCBI's ftp, gunzip, then generated database using above. First few lines of prot.accession2taxid.FULL look like:
```
accession.version       taxid
0308206A        8058
0308221A        9606
0308230A        1049
```

BASTA call:
`basta sequence Diamond_out/West_1_test.tsv basta_out/basta_west_1_fulldb.txt basta_prot_full --directory /caitlin/Cyanobacteria/`

**Comment by timkahlke** [comment]
Yes, that's the problem. BASTA does not remove anything from the names in the mapping files, only from the names in the hits, i.e., it assumes that the mapping files contain the accession number (not version) in the first column. Can I ask why you created your own mapping database instead of just using BASTA's default way of doing it? Is it because you wanted the "full" one? I might be wrong but I don't think that it contains more accession numbers than the default one but, as you just experienced, contains all versions of the different accession numbers. If you are not after the exact versions of a sequence (which usually doesn't matter because you will already have the correct version in your sequence database for your diamond call) then I recommend you just use BASTA's  `basta download prot` and, if you want to include uniprot, too, `basta download uni` to create the mapping dbs. After that you just need to use the "prot" type in your BASTA calls to use that mapping file.

**Comment by ceolder** [comment]
I used diamond with the full version of the file so just wanted to keep working with that one in case there were any missing from the not full version. I'm not entirely sure if it does contain more accession numbers or not, but the readme on the ncbi ftp where the files are located says the full including mapping for all live protein sequence records including GI-less WGS proteins, which makes me think it could. I went ahead and formatted the prot.accession2taxid.FULL to remove the version number and it's now working. 
Thank you for your help!
